include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    non_constant_identifier_names: ignore
    avoid_print: ignore
    use_build_context_synchronously: ignore
    library_private_types_in_public_api: ignore
    no_leading_underscores_for_local_identifiers: ignore
    deprecated_member_use: ignore
    constant_identifier_names: ignore
