name: jcsd_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0
  supabase_flutter: ^2.8.0
  flutter_riverpod: ^2.6.1
  datepicker_dropdown: ^0.1.5
  month_picker_dialog: ^5.1.3
  flutter_launcher_icons: ^0.14.1
  hooks_riverpod: ^2.6.1
  pdf: ^3.11.1
  flutter_email_sender: ^6.0.3
  path_provider: ^2.0.14
  fl_chart: ^0.69.2
  google_sign_in: ^6.2.2
  shimmer: ^3.0.0
  go_router: ^14.8.1
  fluttertoast: ^8.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_mobile.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo_mobile.png"

  web:
    generate: true
    image_path: "assets/images/logo_mobile.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"

  windows:
    generate: true
    image_path: "assets/images/logo_mobile.png"
    icon_size: 48
  
  macos:
    generate: true
    image_path: "assets/images/logo_mobile.png"

flutter:
  uses-material-design: true
  assets:
    #Images
    - assets/images/
    - assets/avatars/
    - assets/icons/

    #Fonts
    - assets/fonts/Nunito-Regular.ttf
    - assets/fonts/Nunito-Bold.ttf
    - assets/fonts/NunitoSans-Regular.ttf
    - assets/fonts/NunitoSans-Bold.ttf
    - assets/fonts/Poppins-Light.ttf
    - assets/fonts/Poppins-Regular.ttf

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans-Regular.ttf
        - asset: assets/fonts/NunitoSans-Bold.ttf
          weight: 800
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
